spring:
  application:
    name: pawever-backend

  datasource:
    url: jdbc:mariadb://localhost:23306/pawever
    username: pawever
    password: pawever1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: pawever-jwt-secret-key-must-be-at-least-256-bits-long-for-hs256-algorithm
  expiration: 86400000  # 24 hours

kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}

naver:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}
  redirect-uri: http://localhost:28080/oauth/naver/callback

cloud:
  ncp:
    credentials:
      access-key: ${NCP_ACCESS_KEY}
      secret-key: ${NCP_SECRET_KEY}
    region: kr-standard
    s3:
      endpoint: https://kr.object.ncloudstorage.com
      bucket: ${NCP_BUCKET}
    cdn:
      domain: ${NCP_CDN_DOMAIN}

